server:
  port: 9095
spring:
  application:
    name: wallet
  ## Database Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop #update
    database-platform:
  datasource:
##    In Memory
    url: jdbc:h2:mem:testdb
    ##    To persist
    #    url: jdbc:h2:file:/home/tharindu/IdeaProjects/data
    driver-class-name: org.h2.Driver
    password: password
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false #prevent trace output
        web-allow-others: false # disable remote access
logging:
  level:
    io.tharindu: error
#customizing actuator endpoints
management:
  endpoints:
    web:
      base-path: /monitoring
      path-mapping:
        info: /information
      exposure:
        include: "*"
        exclude: "env,beans"
#customizing /actuator/info which is accessible via monitoring/information
info:
  app:
    name: wallet
    description: a simple wallet function.